### ISSUE TITLE
Make the prompt more visible/annnoying

### ISSUE THREAD

**Issue by rugk** [JohnMcLear/ep_prompt_for_name#1]
Currently it just opens the usual input box for the user name. However this small little prompt in one corner of your screen is a bit too less IMHO.

I would like it if the prompt would appear directly in the middle of the screen, without a cancel button (or a cancel button, which is only clickable after waiting 5 seconds or so - this is a known system for downloads in Firefox e.g.) and a prompt to enter the correct name when a user just clicks on okay without entering a name.

This way most users will give themself a name.

**Comment by JohnMcLear** [comment]
Speaking for users, I would hate this.

I would suggest such a feature would be a new plugin where you are blocking until someone enters their name.

A compromise might be to set some custom CSS (plugin not required):

```
#myuser {
    border-style: solid;
    border-width: 20px;
    border-color: gainsboro;
    padding: 100px;
}
```

**Comment by rugk** [comment]
Hmm, could be optional, I guess.
And as far as the users are concerned, who visited this GitHub issue, at least 1 user upvoted this. So I'd like to doubt how you can "speak for [your] users".

Anyway, I see the problem with annoying prompts and popup. I also the use case, however: IIRC I've made the observation that most users tend to ignore that input box and thus, we'd have pastes with 20 users, who have all useless names and nobody knows who is who…

**Comment by JohnMcLear** [comment]
Well I would welcome another plugin that provides this functionality, I just don't think it belongs here :)
